namechange: Change namespace to balenalib
Signed-off-by: Trong Nghia Nguyen <nghiant2710@gmail.com>

diff --git a/Dockerfile.rpi b/Dockerfile.rpi
--- a/Dockerfile.rpi
+++ b/Dockerfile.rpi
@@ -5,17 +5,6 @@ COPY 01_buildconfig /etc/apt/apt.conf.d/
 COPY entry.sh /usr/bin/entry.sh
 
 RUN mkdir -p /usr/share/man/man1
-RUN ln -s resin-xbuild /usr/bin/cross-build-start \
-	&& ln -s resin-xbuild /usr/bin/cross-build-end
-
-# Tini
-ENV TINI_VERSION 0.14.0
-RUN curl -SLO "http://resin-packages.s3.amazonaws.com/tini/v$TINI_VERSION/tini0.14.0.linux-armv6hf.tar.gz" \
-	&& echo "33a5089c4f222f0504110000e7d3fd0c3c29830a64a19bae4b34f31dcaf6fb31  tini0.14.0.linux-armv6hf.tar.gz" | sha256sum -c - \
-	&& tar -xzf "tini0.14.0.linux-armv6hf.tar.gz" \
-	&& rm "tini0.14.0.linux-armv6hf.tar.gz" \
-    && chmod +x tini \
-    && mv tini /sbin/tini
 
 ENV LC_ALL C.UTF-8
 ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
@@ -27,5 +16,31 @@ LABEL io.balena.architecture="rpi" \
 	  io.balena.device-type="raspberrypi"
 
 ENV QEMU_CPU arm1176
+
+RUN echo '#!/bin/sh\n\
+set -e\n\
+set -u\n\
+export DEBIAN_FRONTEND=noninteractive\n\
+n=0\n\
+max=2\n\
+until [ $n -gt $max ]; do\n\
+  set +e\n\
+  (\n\
+    apt-get update -qq &&\n\
+    apt-get install -y --no-install-recommends "$@"\n\
+  )\n\
+  CODE=$?\n\
+  set -e\n\
+  if [ $CODE -eq 0 ]; then\n\
+    break\n\
+  fi\n\
+  if [ $n -eq $max ]; then\n\
+    exit $CODE\n\
+  fi\n\
+  echo "apt failed, retrying"\n\
+  n=$(($n + 1))\n\
+done\n\
+rm -r /var/lib/apt/lists/*' > /usr/sbin/install_packages \
+  && chmod 0755 "/usr/sbin/install_packages"
 
 ENTRYPOINT ["/usr/bin/entry.sh"]
